"use client";

import { CalendarDays, CheckCircle2, Clock3, CreditCard, Download, MapPin, RefreshCcw, Scissors, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { money } from "@/lib/format";
import { localDateTimeParts, zonedDateTimeToUtc } from "@/lib/booking-time";

function localDate(value: string){return new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date(`${value}T12:00:00`))}
function humanTime(value:string){const[h,m]=value.slice(0,5).split(":").map(Number);const d=new Date();d.setHours(h,m);return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(d)}

export function CustomerPortal({ token, data }: { token: string; data: any }) {
  const booking=data.booking;const service=Array.isArray(booking.services)?booking.services[0]:booking.services;const barber=Array.isArray(booking.barber_profiles)?booking.barber_profiles[0]:booking.barber_profiles;const policy=data.policy||{};
  const[date,setDate]=useState(booking.appointment_date);const[time,setTime]=useState(booking.appointment_time.slice(0,5));const[slots,setSlots]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");const[showReschedule,setShowReschedule]=useState(false);const paymentProvider="stripe";
  const timezone=barber.timezone||booking.timezone||"America/New_York";const startsAt=useMemo(()=>zonedDateTimeToUtc(booking.appointment_date,booking.appointment_time.slice(0,5),timezone),[booking.appointment_date,booking.appointment_time,timezone]);const localToday=localDateTimeParts(new Date(),timezone).date;const hoursAway=(startsAt.getTime()-Date.now())/3600000;const canCancel=booking.status!=="cancelled"&&booking.status!=="completed"&&policy.customer_cancellation_enabled!==false;const canReschedule=booking.status!=="cancelled"&&booking.status!=="completed"&&policy.customer_reschedule_enabled!==false&&booking.reschedule_count<Number(policy.max_reschedules??2);
  async function loadSlots(nextDate:string){setDate(nextDate);setTime("");setLoading(true);const params=new URLSearchParams({barberSlug:barber.slug,serviceId:service.id,date:nextDate});const response=await fetch(`/api/availability?${params}`);const payload=await response.json();setSlots(Array.isArray(payload.slots)?payload.slots:[]);setLoading(false)}
  async function action(actionName:string,extra:any={}){setLoading(true);setMessage("");const response=await fetch(`/api/customer/booking/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:actionName,...extra})});const payload=await response.json();if(!response.ok){setMessage(payload.error||"Request failed.");setLoading(false);return}setMessage(payload.message||"Appointment updated.");setTimeout(()=>window.location.reload(),700)}
  async function payBalance(){setLoading(true);const response=await fetch("/api/payments/create-balance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({portalToken:token,paymentProvider})});const payload=await response.json();if(!response.ok){setMessage(payload.error||"Could not open checkout.");setLoading(false);return}window.location.href=payload.url}
  return <main className="customer-portal-page"><section className="customer-portal-shell"><header className="customer-portal-header"><div><p className="eyebrow">MANAGE YOUR APPOINTMENT</p><h1>{barber.shop_name}</h1><p>Booking {booking.booking_code}</p></div><span className={`portal-status ${booking.status}`}><CheckCircle2/>{booking.status.replaceAll("_"," ")}</span></header>
  <div className="portal-grid"><section className="portal-primary glass-card"><div className="portal-date"><CalendarDays/><div><small>APPOINTMENT DATE</small><strong>{localDate(booking.appointment_date)}</strong><span>{humanTime(booking.appointment_time)} · {booking.duration_minutes} minutes</span></div></div><div className="portal-info-list"><div><Scissors/><span><small>SERVICE</small><b>{service?.name}</b></span><strong>{money(booking.service_total_cents)}</strong></div><div><MapPin/><span><small>LOCATION</small><b>{barber.address}</b><span>{barber.city}</span></span></div><div><Clock3/><span><small>BARBER</small><b>{barber.display_name}</b><span>{barber.phone}</span></span></div></div><div className="portal-request"><small>YOUR SAVED REQUEST</small><h3>{booking.haircut_request?.desiredStyle||"Haircut request"}</h3><p>{booking.haircut_request?.texture||"Texture not set"} · {booking.haircut_request?.currentLength||"Length not set"}</p><p>{booking.haircut_request?.referenceNote||"No additional note."}</p></div></section>
  <aside className="portal-payment glass-card"><p className="eyebrow">PAYMENT</p><div><span>Appointment total</span><b>{money(booking.total_cents)}</b></div><div><span>Deposit paid</span><b>-{money(booking.deposit_cents)}</b></div><div className="portal-balance"><span>Remaining balance</span><strong>{money(booking.balance_cents)}</strong></div>{booking.balance_cents>0&&booking.status!=="cancelled"&&<><div className="portal-secure-payment"><CreditCard/><span><b>Secure Stripe checkout</b><small>Pay by card or an eligible digital wallet.</small></span></div><button className="button" onClick={payBalance} disabled={loading||!data.connections.length}><CreditCard/> Pay remaining balance</button></>}<button className="button secondary" onClick={()=>window.print()}><Download/> Print receipt</button></aside></div>
  <section className="portal-actions glass-card"><div><h2>Need to make a change?</h2><p>Changes are controlled by {barber.display_name}’s booking policy. Your current appointment is {Math.max(0,Math.round(hoursAway))} hours away.</p></div><div>{canReschedule&&<button className="button secondary" onClick={()=>setShowReschedule(v=>!v)}><RefreshCcw/> Reschedule</button>}{canCancel&&<button className="button danger" onClick={()=>{if(confirm("Cancel this appointment?"))action("cancel")}}><XCircle/> Cancel appointment</button>}</div></section>
  {showReschedule&&<section className="portal-reschedule glass-card"><header><div><p className="eyebrow">NEW APPOINTMENT TIME</p><h2>Choose another exact opening.</h2></div></header><label><span>Date</span><input type="date" value={date} min={localToday} onChange={e=>loadSlots(e.target.value)}/></label><div className="time-grid">{loading?<p>Checking openings…</p>:slots.map(slot=><button key={slot} className={time===slot?"selected":""} onClick={()=>setTime(slot)}>{humanTime(slot)}</button>)}</div><button className="button" disabled={!date||!time||loading} onClick={()=>action("reschedule",{selectedDate:date,selectedTime:time})}>Confirm new time</button></section>}
  {message&&<div className="portal-message">{message}</div>}<footer className="customer-portal-footer">Secure appointment access powered by CutFlow. Keep this private link for your records.</footer></section></main>
}
