"use client";

import { ArrowDownToLine, CheckCircle2, CreditCard, Download, Plus, RefreshCcw, Search, SlidersHorizontal, WalletCards, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { transactions as seedTransactions } from "@/lib/demo-data";
import { money, shortDate } from "@/lib/format";
import { StatusPill } from "@/components/StatusPill";
import type { Transaction } from "@/lib/types";

const blank={customerName:"",type:"cash",amount:"",method:"Cash",note:""};
export default function PaymentsPage(){
  const[transactions,setTransactions]=useState<Transaction[]>(seedTransactions);
  const[query,setQuery]=useState("");const[typeFilter,setTypeFilter]=useState("all");const[showRecord,setShowRecord]=useState(false);const[form,setForm]=useState(blank);const[saving,setSaving]=useState(false);
  useEffect(()=>{fetch("/api/dashboard/data?resource=transactions").then(r=>r.json()).then(payload=>{if(Array.isArray(payload.data))setTransactions(payload.data)}).catch(()=>undefined)},[]);
  const filtered=useMemo(()=>transactions.filter(item=>{const matchesQuery=`${item.customerName} ${item.type} ${item.method} ${item.id}`.toLowerCase().includes(query.toLowerCase());const matchesType=typeFilter==="all"||item.type===typeFilter;return matchesQuery&&matchesType}),[transactions,query,typeFilter]);
  const gross=transactions.filter(item=>item.status==="paid").reduce((sum,item)=>sum+item.grossCents,0);const deposits=transactions.filter(item=>item.type==="deposit"&&item.status==="paid").reduce((sum,item)=>sum+item.grossCents,0);const net=transactions.reduce((sum,item)=>sum+item.netCents,0);const refunds=transactions.filter(item=>item.type==="refund"||item.status==="refunded").reduce((sum,item)=>sum+Math.abs(item.grossCents),0);
  function download(){const rows=[["ID","Date","Customer","Type","Gross","Tax","Processor Fee","Net","Method","Status"],...transactions.map(item=>[item.id,item.date,item.customerName,item.type,(item.grossCents/100).toFixed(2),(item.taxCents/100).toFixed(2),(item.processorFeeCents/100).toFixed(2),(item.netCents/100).toFixed(2),item.method,item.status])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="cutflow-transactions.csv";a.click();URL.revokeObjectURL(url)}
  async function record(){setSaving(true);const response=await fetch("/api/dashboard/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"transaction",item:form})});const payload=await response.json();if(response.ok&&Array.isArray(payload.data)){setTransactions(payload.data);setShowRecord(false);setForm(blank)}setSaving(false)}
  return <div className="dashboard-page payments-page"><header className="page-header"><div><p className="eyebrow">DIRECT BARBER REVENUE</p><h1>Payments</h1><p>Track deposits, service balances, products, cash and refunds in one transaction history.</p></div><div className="page-actions"><button className="button secondary" onClick={download}><Download/> Export</button><button className="button" onClick={()=>setShowRecord(true)}><Plus/> Record payment</button></div></header>
  <section className="metric-grid"><article className="metric-card glass-card"><span className="metric-icon"><WalletCards/></span><p>Gross collected</p><strong>{money(gross)}</strong><small>Services + products + tips</small></article><article className="metric-card glass-card"><span className="metric-icon"><CreditCard/></span><p>Deposits collected</p><strong>{money(deposits)}</strong><small>Paid chair reservations</small></article><article className="metric-card glass-card"><span className="metric-icon"><ArrowDownToLine/></span><p>Recorded net</p><strong>{money(net)}</strong><small>After processor fees</small></article><article className="metric-card glass-card"><span className="metric-icon"><RefreshCcw/></span><p>Refunds</p><strong>{money(refunds)}</strong><small>Recorded returns</small></article></section>
  <section className="payment-flow-banner"><div><span><CheckCircle2/></span><div><b>Client payments route directly to the connected barber account.</b><p>CutFlow does not remove an application percentage. The processor’s normal payment fee appears separately in reporting.</p></div></div><Link className="button secondary" href="/dashboard/connections">Manage payment connections</Link></section>
  <div className="table-toolbar dashboard-card"><label className="search-field"><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search transaction, client or method"/></label><label className="transaction-filter"><SlidersHorizontal/><span className="sr-only">Filter by transaction type</span><select value={typeFilter} onChange={(event)=>setTypeFilter(event.target.value)}><option value="all">All transaction types</option><option value="deposit">Deposits</option><option value="service_balance">Service balances</option><option value="product">Products</option><option value="tip">Tips</option><option value="cash">Cash services</option><option value="refund">Refunds</option></select></label></div>
  <section className="transaction-table dashboard-card"><header><span>Transaction</span><span>Type</span><span>Gross</span><span>Tax</span><span>Processor fee</span><span>Net</span><span>Status</span></header>{filtered.map(item=><div className="transaction-row" key={item.id}><span><i className="transaction-icon"><CreditCard/></i><span><b>{item.customerName}</b><small>{item.id} · {shortDate(item.date)}</small><small>{item.method}</small></span></span><span><b>{item.type.replaceAll("_"," ")}</b><small>{item.bookingId||"Counter sale"}</small></span><span><b>{money(item.grossCents)}</b></span><span>{money(item.taxCents)}</span><span>-{money(item.processorFeeCents)}</span><span><b>{money(item.netCents)}</b></span><StatusPill status={item.status}/></div>)}</section>
  {showRecord&&<div className="modal-scrim"><div className="modal-card glass-card"><header><div><p className="eyebrow">MANUAL TRANSACTION</p><h2>Record cash or external payment.</h2></div><button className="icon-button" onClick={()=>setShowRecord(false)}><X/></button></header><div className="form-grid two"><label><span>Client / description</span><input value={form.customerName} onChange={event=>setForm({...form,customerName:event.target.value})} placeholder="Client name"/></label><label><span>Type</span><select value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option value="cash">Cash service</option><option value="service_balance">Service balance</option><option value="product">Product</option><option value="tip">Tip</option><option value="deposit">Deposit</option><option value="refund">Refund</option></select></label><label><span>Amount</span><div className="money-input"><span>$</span><input value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})} placeholder="0.00"/></div></label><label><span>Method</span><select value={form.method} onChange={event=>setForm({...form,method:event.target.value})}><option>Cash</option><option>External card terminal</option><option>Cash App</option><option>Venmo</option><option>Other</option></select></label><label className="full"><span>Note</span><textarea value={form.note} onChange={event=>setForm({...form,note:event.target.value})} placeholder="Optional internal note"/></label></div><footer><button className="button secondary" onClick={()=>setShowRecord(false)}>Cancel</button><button className="button" disabled={saving||!form.amount} onClick={record}>{saving?"Saving…":"Save transaction"}</button></footer></div></div>}</div>}
