"use client";

import { Check, CircleAlert, LoaderCircle, PlugZap, RefreshCcw, ShieldCheck, Unplug, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { HelpTip } from "@/components/HelpTip";

type Connection = { provider: "stripe"|"square"|"paypal"; label: string; description: string; customerMethods: string[]; status: string; chargesEnabled: boolean; payoutsEnabled: boolean; verificationStatus: string; environmentReady: boolean; lastSyncedAt?: string|null; lastError?: string|null; externalAccountId?: string|null };

export function PaymentConnections(){const[data,setData]=useState<{primaryProvider:string|null;connections:Connection[]}|null>(null);const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/payments/connections");const p=await r.json();if(r.ok)setData(p)}
  useEffect(()=>{load()},[])
  async function post(url:string,provider:string){setBusy(provider);setMessage("");const r=await fetch(url,{method:"POST"});const p=await r.json().catch(()=>({}));if(!r.ok)setMessage(p.error||"Action failed.");await load();setBusy("")}
  async function setPrimary(provider:string){setBusy(provider);setMessage("");const r=await fetch("/api/payments/primary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider})});const p=await r.json().catch(()=>({}));if(!r.ok)setMessage(p.error||"Could not set primary provider.");await load();setBusy("")}
  if(!data)return <div className="dashboard-card loading-card"><LoaderCircle className="spin"/> Loading payment connections…</div>;
  return <><section className="connections-intro dashboard-card"><div><span className="connection-hero-icon"><WalletCards/></span><div><p className="eyebrow">SIGN IN. CONNECT. GET PAID.</p><h2>No API keys for barbers. <HelpTip text="CutFlow holds the platform credentials securely. You only sign in to your own payment account and approve the connection."/></h2><p>CutFlow opens each provider’s secure setup. For Stripe, the barber completes Stripe-hosted business, identity and payout onboarding, then returns here.</p></div></div><ul><li><Check/>Customer money goes through the barber’s connected account.</li><li><Check/>CutFlow’s appointment application fee is set to $0.</li><li><Check/>Provider processing fees still apply.</li></ul></section>
  <section className="connection-grid">{data.connections.map(item=>{const ready=item.status==="connected"&&item.chargesEnabled;return <article className={`connection-card dashboard-card ${ready?"ready":""}`} key={item.provider}><header><span className={`provider-logo ${item.provider}`}>{item.provider==="stripe"?"S":item.provider==="square"?"□":"P"}</span><div><h3>{item.label}</h3><p>{item.description}</p></div><span className={`connection-status ${ready?"connected":item.status}`}>{ready?<ShieldCheck/>:<CircleAlert/>}{ready?"Connected":item.status.replaceAll("_"," ")}</span></header><div className="method-chip-row">{item.customerMethods.map(method=><span key={method}>{method}</span>)}</div><dl><div><dt>Accepting payments <HelpTip text="Yes means this provider currently allows CutFlow to create customer checkouts for your account."/></dt><dd>{item.chargesEnabled?"Yes":"Not yet"}</dd></div><div><dt>Payout ready <HelpTip text="Yes means the provider has enough identity and bank information to send your money."/></dt><dd>{item.payoutsEnabled?"Yes":"Not yet"}</dd></div><div><dt>Verification <HelpTip text="Requirements due means the provider needs additional business, identity or bank information."/></dt><dd>{item.verificationStatus.replaceAll("_"," ")}</dd></div></dl>{item.lastError&&<p className="connection-error">{item.lastError}</p>}<footer>{!item.environmentReady?<span className="connection-config-note">Not available yet</span>:!ready?<a className="button" href={`/api/payments/connect/${item.provider}`}><PlugZap/> {item.provider === "stripe" && item.externalAccountId ? "Continue Stripe setup" : `Connect ${item.label}`}</a>:<><button className="button secondary" disabled={busy===item.provider} onClick={()=>post(`/api/payments/sync/${item.provider}`,item.provider)}><RefreshCcw/> Refresh</button><button className="button ghost-danger" disabled={busy===item.provider} onClick={()=>confirm(`Disconnect ${item.label}?`)&&post(`/api/payments/disconnect/${item.provider}`,item.provider)}><Unplug/> {item.provider === "stripe" ? "Stop using Stripe" : "Disconnect"}</button></>} {ready&&data.primaryProvider!==item.provider&&<button className="button" disabled={busy===item.provider} onClick={()=>setPrimary(item.provider)}>Make primary</button>}{data.primaryProvider===item.provider&&<span className="primary-badge"><Check/> Primary checkout</span>}</footer></article>})}</section>
  <section className="provider-notes dashboard-card"><div><h3>PayPal and Venmo availability</h3><p>CutFlow manages the platform approval and technical setup. When this option becomes available, you will only sign in to PayPal and approve the connection—no developer account or API keys are required from you.</p></div><span className="connection-config-note">Managed by CutFlow</span></section>{message&&<p className="form-error">{message}</p>}</>}
