import type { Barber, Booking, Customer, Product, Service, Transaction } from "./types";

export const demoBarber: Barber = {
  id: "barber-demo",
  slug: "marcus-studio",
  displayName: "Marcus Reed",
  shopName: "REED / Studio",
  headline: "Precision cuts. Calm chair. No rushed appointments.",
  bio: "A private, detail-first barbering experience built around consistency. Your preferences stay on file, so every return visit starts ahead.",
  address: "214 Union Street",
  city: "New Bedford, MA",
  phone: "(508) 555-0143",
  email: "marcus@example.com",
  accent: "#d8ff5f",
  stripeConnected: true,
  acceptingBookings: true,
};

export const services: Service[] = [
  {
    id: "signature-cut",
    name: "Signature Cut",
    description: "Consultation, tailored haircut, line-up, hot towel finish and style.",
    durationMinutes: 45,
    priceCents: 4500,
    category: "Haircut",
    active: true,
    addOns: ["Beard detail", "Enhancements", "Scalp treatment"],
  },
  {
    id: "cut-beard",
    name: "Cut + Beard",
    description: "Full haircut with beard shape, razor line and conditioning finish.",
    durationMinutes: 60,
    priceCents: 6000,
    category: "Combination",
    active: true,
    addOns: ["Enhancements", "Hot towel mask"],
  },
  {
    id: "shape-up",
    name: "Shape-Up",
    description: "Crisp hairline, neck clean-up and light taper maintenance.",
    durationMinutes: 25,
    priceCents: 2800,
    category: "Maintenance",
    active: true,
  },
  {
    id: "kids-cut",
    name: "Young King Cut",
    description: "Patient, comfortable haircut experience for ages 6–12.",
    durationMinutes: 35,
    priceCents: 3500,
    category: "Kids",
    active: true,
  },
  {
    id: "loc-maintenance",
    name: "Loc Edge + Taper",
    description: "Clean perimeter, taper, line-up and finish around locs or braids.",
    durationMinutes: 40,
    priceCents: 4200,
    category: "Protective styles",
    active: true,
  },
];

export const products: Product[] = [
  {
    id: "curl-cream",
    name: "Daily Curl Cream",
    description: "Light moisture and definition without crunch or buildup.",
    priceCents: 1800,
    inventory: 14,
    textureTags: ["3A", "3B", "3C", "4A"],
    serviceTags: ["signature-cut", "loc-maintenance"],
    pickupOnly: true,
    active: true,
  },
  {
    id: "wave-pomade",
    name: "Soft Hold Wave Pomade",
    description: "Low-shine hold for waves, crops and brushed styles.",
    priceCents: 1600,
    inventory: 8,
    textureTags: ["2C", "3A", "3B", "4A"],
    serviceTags: ["signature-cut", "shape-up"],
    pickupOnly: true,
    active: true,
  },
  {
    id: "beard-oil",
    name: "Cedar Beard Oil",
    description: "Softens coarse beard hair and reduces dry skin beneath it.",
    priceCents: 2200,
    inventory: 11,
    textureTags: ["all"],
    serviceTags: ["cut-beard"],
    pickupOnly: true,
    active: true,
  },
  {
    id: "scalp-tonic",
    name: "Cooling Scalp Tonic",
    description: "Post-cut refresh for dry, tight or sensitive scalps.",
    priceCents: 1900,
    inventory: 5,
    textureTags: ["all"],
    serviceTags: ["signature-cut", "kids-cut", "loc-maintenance"],
    pickupOnly: true,
    active: true,
  },
];

const defaultRequest = {
  texture: "4A",
  currentLength: "Short / 1–2 inches",
  desiredStyle: "Low taper with textured top",
  sides: "Low taper, keep darkness above temple",
  top: "Scissor shape only; keep length",
  lineUp: true,
  beard: "Short boxed beard, natural cheek line",
  enhancements: false,
  sensitivity: "Sensitive near right temple",
  referenceNote: "Keep the front corners natural. Do not push the line back.",
  repeatLastRequest: true,
};

export const customers: Customer[] = [
  {
    id: "customer-1",
    name: "Jordan Miles",
    email: "jordan@example.com",
    phone: "(508) 555-0191",
    joinedAt: "2025-11-18",
    visits: 14,
    lifetimeValueCents: 78200,
    lastVisit: "2026-07-10",
    texture: "4A",
    preferredStyle: "Low taper + textured top",
    allergies: "Avoid heavily fragranced products",
    notes: "Prefers quiet appointments. Usually buys scalp tonic.",
    lastRequest: defaultRequest,
  },
  {
    id: "customer-2",
    name: "Andre Collins",
    email: "andre@example.com",
    phone: "(774) 555-0144",
    joinedAt: "2026-02-02",
    visits: 7,
    lifetimeValueCents: 40800,
    lastVisit: "2026-07-15",
    texture: "3C",
    preferredStyle: "Burst fade + curls",
    allergies: "None noted",
    notes: "Books every other Thursday after 5 PM.",
    lastRequest: { ...defaultRequest, texture: "3C", desiredStyle: "Burst fade with curl definition" },
  },
  {
    id: "customer-3",
    name: "Malik Thomas",
    email: "malik@example.com",
    phone: "(617) 555-0180",
    joinedAt: "2026-06-08",
    visits: 2,
    lifetimeValueCents: 9000,
    lastVisit: "2026-07-01",
    texture: "4C",
    preferredStyle: "High taper around locs",
    allergies: "Tea tree sensitivity",
    notes: "New loc client. Photograph taper result next visit with permission.",
    lastRequest: { ...defaultRequest, texture: "4C", desiredStyle: "High taper around locs", beard: "No beard service" },
  },
];

export const bookings: Booking[] = [
  {
    id: "BK-1048",
    customerId: "customer-2",
    customerName: "Andre Collins",
    customerEmail: "andre@example.com",
    customerPhone: "(774) 555-0144",
    serviceId: "cut-beard",
    serviceName: "Cut + Beard",
    startsAt: "2026-07-20T09:00:00-04:00",
    endsAt: "2026-07-20T10:00:00-04:00",
    status: "confirmed",
    totalCents: 6000,
    depositCents: 1000,
    balanceCents: 5000,
    paymentStatus: "deposit_paid",
    haircutRequest: customers[1].lastRequest,
    productIds: ["beard-oil"],
  },
  {
    id: "BK-1049",
    customerId: "customer-1",
    customerName: "Jordan Miles",
    customerEmail: "jordan@example.com",
    customerPhone: "(508) 555-0191",
    serviceId: "signature-cut",
    serviceName: "Signature Cut",
    startsAt: "2026-07-20T10:30:00-04:00",
    endsAt: "2026-07-20T11:15:00-04:00",
    status: "confirmed",
    totalCents: 6400,
    depositCents: 1000,
    balanceCents: 5400,
    paymentStatus: "deposit_paid",
    haircutRequest: customers[0].lastRequest,
    productIds: ["scalp-tonic"],
  },
  {
    id: "BK-1050",
    customerId: "customer-3",
    customerName: "Malik Thomas",
    customerEmail: "malik@example.com",
    customerPhone: "(617) 555-0180",
    serviceId: "loc-maintenance",
    serviceName: "Loc Edge + Taper",
    startsAt: "2026-07-20T12:00:00-04:00",
    endsAt: "2026-07-20T12:40:00-04:00",
    status: "confirmed",
    totalCents: 4200,
    depositCents: 1000,
    balanceCents: 3200,
    paymentStatus: "deposit_paid",
    haircutRequest: customers[2].lastRequest,
    productIds: [],
  },
  {
    id: "BK-1051",
    customerId: "customer-4",
    customerName: "Elijah Grant",
    customerEmail: "elijah@example.com",
    customerPhone: "(508) 555-0108",
    serviceId: "shape-up",
    serviceName: "Shape-Up",
    startsAt: "2026-07-20T14:15:00-04:00",
    endsAt: "2026-07-20T14:40:00-04:00",
    status: "pending_deposit",
    totalCents: 2800,
    depositCents: 1000,
    balanceCents: 1800,
    paymentStatus: "deposit_due",
    haircutRequest: { ...defaultRequest, texture: "3B", desiredStyle: "Line-up and taper clean-up" },
    productIds: ["wave-pomade"],
  },
];

export const transactions: Transaction[] = [
  { id: "TX-901", bookingId: "BK-1048", customerName: "Andre Collins", date: "2026-07-15", type: "deposit", grossCents: 1000, taxCents: 0, processorFeeCents: 59, netCents: 941, method: "Visa •••• 3812", status: "paid" },
  { id: "TX-902", bookingId: "BK-1047", customerName: "Darnell Price", date: "2026-07-15", type: "service_balance", grossCents: 5000, taxCents: 0, processorFeeCents: 175, netCents: 4825, method: "Apple Pay", status: "paid" },
  { id: "TX-903", customerName: "Darnell Price", date: "2026-07-15", type: "product", grossCents: 2200, taxCents: 138, processorFeeCents: 94, netCents: 2106, method: "Apple Pay", status: "paid" },
  { id: "TX-904", bookingId: "BK-1049", customerName: "Jordan Miles", date: "2026-07-16", type: "deposit", grossCents: 1000, taxCents: 0, processorFeeCents: 59, netCents: 941, method: "Mastercard •••• 1129", status: "paid" },
  { id: "TX-905", bookingId: "BK-1046", customerName: "Devon King", date: "2026-07-16", type: "cash", grossCents: 4500, taxCents: 0, processorFeeCents: 0, netCents: 4500, method: "Cash", status: "paid" },
  { id: "TX-906", bookingId: "BK-1050", customerName: "Malik Thomas", date: "2026-07-17", type: "deposit", grossCents: 1000, taxCents: 0, processorFeeCents: 59, netCents: 941, method: "Visa •••• 0044", status: "paid" },
  { id: "TX-907", bookingId: "BK-1045", customerName: "Isaiah Cole", date: "2026-07-18", type: "service_balance", grossCents: 3500, taxCents: 0, processorFeeCents: 132, netCents: 3368, method: "Cash App Pay", status: "paid" },
];

export const weeklyRevenue = [
  { label: "Mon", value: 480 },
  { label: "Tue", value: 620 },
  { label: "Wed", value: 540 },
  { label: "Thu", value: 860 },
  { label: "Fri", value: 1130 },
  { label: "Sat", value: 1480 },
  { label: "Sun", value: 0 },
];

export const availability = {
  0: [],
  1: [["09:00", "18:00"]],
  2: [["09:00", "18:00"]],
  3: [["10:00", "19:00"]],
  4: [["10:00", "20:00"]],
  5: [["09:00", "20:00"]],
  6: [["08:00", "17:00"]],
} as Record<number, string[][]>;
