"use client";

import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Filter, Mail, MoreHorizontal, Phone, Plus, Search, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { StatusPill } from "@/components/StatusPill";
import { bookings as seedBookings, services as seedServices } from "@/lib/demo-data";
import { initials, money } from "@/lib/format";
import type { Booking, BookingStatus, Service } from "@/lib/types";

const tomorrow=()=>{const date=new Date();date.setDate(date.getDate()+1);return date.toISOString().slice(0,10)};
const blankBooking=()=>({name:"",email:"",phone:"",serviceId:"",date:tomorrow(),time:"09:00",request:""});
export default function BookingsPage() {
  const [bookings, setBookings] = useState<Booking[]>(seedBookings);
  const [services,setServices]=useState<Service[]>(seedServices);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [scheduleDate, setScheduleDate] = useState("");
  const [selected, setSelected] = useState<Booking | null>(seedBookings[0]);
  const [showAdd, setShowAdd] = useState(false);
  const [form,setForm]=useState(blankBooking());
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState("");

  useEffect(()=>{Promise.all([fetch("/api/dashboard/data?resource=bookings").then(r=>r.json()),fetch("/api/dashboard/data?resource=services").then(r=>r.json())]).then(([bookingPayload,servicePayload])=>{if(Array.isArray(bookingPayload.data)){setBookings(bookingPayload.data);setSelected(bookingPayload.data[0]||null)}if(Array.isArray(servicePayload.data)){setServices(servicePayload.data);setForm(current=>({...current,serviceId:servicePayload.data[0]?.id||""}))}}).catch(()=>undefined)},[]);
  const filtered = useMemo(() => bookings.filter((booking) => {
    const matchesQuery = `${booking.customerName} ${booking.serviceName} ${booking.id}`.toLowerCase().includes(query.toLowerCase());
    const matchesStatus = status === "all" || booking.status === status;
    const bookingDay = new Date(booking.startsAt).toLocaleDateString("en-CA");
    const matchesDate = !scheduleDate || bookingDay === scheduleDate;
    return matchesQuery && matchesStatus && matchesDate;
  }).sort((a,b)=>+new Date(a.startsAt)-+new Date(b.startsAt)), [bookings, query, status, scheduleDate]);
  function moveScheduleDay(amount:number){const base=scheduleDate?new Date(`${scheduleDate}T12:00:00`):new Date();base.setDate(base.getDate()+amount);setScheduleDate(base.toLocaleDateString("en-CA"))}
  const scheduleLabel=scheduleDate?new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date(`${scheduleDate}T12:00:00`)):"Upcoming appointments";

  async function updateStatus(id: string, next: BookingStatus) {
    setBookings((current) => current.map((booking) => booking.id === id ? { ...booking, status: next } : booking));
    setSelected((current) => current?.id === id ? { ...current, status: next } : current);
    await fetch("/api/dashboard/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"booking_status",id,status:next})});
  }
  async function createBooking(){setSaving(true);setError("");const response=await fetch("/api/dashboard/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"booking",item:{...form,haircutRequest:{desiredStyle:form.request,texture:"",currentLength:"",sides:"",top:"",lineUp:true,beard:"No beard service",enhancements:false,sensitivity:"",referenceNote:form.request,repeatLastRequest:false}}})});const payload=await response.json();if(response.ok&&Array.isArray(payload.data)){setBookings(payload.data);setShowAdd(false);setForm({...blankBooking(),serviceId:services[0]?.id||""})}else setError(payload.error||"Could not create booking.");setSaving(false)}
  const deposits=bookings.filter(item=>item.paymentStatus==="deposit_paid"||item.paymentStatus==="paid").reduce((sum,item)=>sum+item.depositCents,0);
  return <div className="dashboard-page bookings-page">
    <header className="page-header"><div><p className="eyebrow">CHAIR CALENDAR</p><h1>Bookings</h1><p>See exact times, deposits, requests and remaining balances before the day starts.</p></div><button className="button" onClick={()=>setShowAdd(true)}><Plus/> Add booking</button></header>
    <div className="booking-toolbar dashboard-card"><div className="date-navigator"><button className="icon-button" aria-label="Previous day" onClick={()=>moveScheduleDay(-1)}><ChevronLeft/></button><div><small>ACTIVE SCHEDULE</small><b>{scheduleLabel}</b></div><button className="icon-button" aria-label="Next day" onClick={()=>moveScheduleDay(1)}><ChevronRight/></button><button className="text-button" onClick={()=>setScheduleDate(new Date().toLocaleDateString("en-CA"))}>Today</button>{scheduleDate&&<button className="text-button" onClick={()=>setScheduleDate("")}>All upcoming</button>}</div><div className="toolbar-filters"><label className="search-field"><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search bookings"/></label><label className="select-field"><Filter/><select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="confirmed">Confirmed</option><option value="pending_deposit">Deposit pending</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label></div></div>
    <section className="bookings-workspace">
      <article className="dashboard-card booking-timeline"><header><div><span className="live-indicator">●</span><b>{filtered.length} appointments</b><small>Live chair schedule</small></div><span>{money(deposits)} deposits collected</span></header><div className="timeline-list">{filtered.map((booking,index)=><button key={booking.id} className={selected?.id===booking.id?"timeline-booking selected":"timeline-booking"} onClick={()=>setSelected(booking)}><time><b>{new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(booking.startsAt))}</b><small>{new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(booking.endsAt))}</small></time><i className={`timeline-line line-${booking.status}`}/><span className="avatar">{initials(booking.customerName)}</span><div><b>{booking.customerName}</b><span>{booking.serviceName}</span><small>{booking.haircutRequest?.desiredStyle||"No request saved"}</small></div><div className="timeline-status"><StatusPill status={booking.status}/><b>{money(booking.balanceCents)} due</b></div><MoreHorizontal/></button>)}{filtered.length===0&&<div className="empty-selection"><CalendarDays/><p>No bookings match these filters.</p></div>}</div></article>
      <aside className="dashboard-card booking-inspector">{selected?<><header><div><p className="eyebrow">{selected.id}</p><h2>{selected.customerName}</h2><span>{selected.serviceName}</span></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></header><div className="booking-inspector-time"><CalendarDays/><div><small>EXACT APPOINTMENT</small><b>{new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date(selected.startsAt))}</b><span>{new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(selected.startsAt))}–{new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(selected.endsAt))}</span></div></div><div className="inspector-contact"><a href={`tel:${selected.customerPhone}`}><Phone/> {selected.customerPhone}</a><a href={`mailto:${selected.customerEmail}`}><Mail/> {selected.customerEmail}</a></div><hr/><section><small className="section-label">HAIRCUT REQUEST</small><div className="request-summary"><div><span>Style</span><b>{selected.haircutRequest?.desiredStyle||"Not set"}</b></div><div><span>Texture</span><b>{selected.haircutRequest?.texture||"Not set"}</b></div><div><span>Sides</span><b>{selected.haircutRequest?.sides||"Not set"}</b></div><div><span>Top</span><b>{selected.haircutRequest?.top||"Not set"}</b></div><div><span>Beard</span><b>{selected.haircutRequest?.beard||"Not set"}</b></div><div><span>Sensitivity</span><b>{selected.haircutRequest?.sensitivity||"None noted"}</b></div></div>{selected.haircutRequest?.repeatLastRequest&&<div className="repeat-pill">↻ Repeated from last appointment</div>}</section><hr/><section><small className="section-label">PAYMENT</small><div className="payment-summary"><div><span>Appointment total</span><b>{money(selected.totalCents)}</b></div><div><span>Deposit</span><b>-{money(selected.depositCents)}</b></div><div className="balance"><span>Due after service</span><strong>{money(selected.balanceCents)}</strong></div></div></section><footer><select value={selected.status} onChange={(event)=>updateStatus(selected.id,event.target.value as BookingStatus)}><option value="pending_deposit">Deposit pending</option><option value="confirmed">Confirmed</option><option value="checked_in">Checked in</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select><Link className="button" href={`/dashboard/clients/${selected.customerId}`}>Open client profile</Link></footer></>:<div className="empty-selection"><Clock3/><p>Select a booking to inspect the request.</p></div>}</aside>
    </section>
    {showAdd&&<div className="modal-scrim"><div className="modal-card glass-card"><header><div><p className="eyebrow">MANUAL BOOKING</p><h2>Add a call-in or walk-in.</h2></div><button className="icon-button" onClick={()=>setShowAdd(false)}><X/></button></header><div className="form-grid two"><label><span>Client name</span><input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Client name"/></label><label><span>Phone</span><input value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})} placeholder="(508) 555-0123"/></label><label className="full"><span>Email</span><input value={form.email} onChange={event=>setForm({...form,email:event.target.value})} type="email" placeholder="client@example.com"/></label><label><span>Service</span><select value={form.serviceId} onChange={event=>setForm({...form,serviceId:event.target.value})}>{services.map(service=><option value={service.id} key={service.id}>{service.name}</option>)}</select></label><label><span>Date</span><input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></label><label><span>Start time</span><input type="time" value={form.time} onChange={event=>setForm({...form,time:event.target.value})}/></label><label className="full"><span>Haircut request</span><textarea value={form.request} onChange={event=>setForm({...form,request:event.target.value})} placeholder="Add request details or load the client’s saved request."/></label></div>{error&&<p className="form-error">{error}</p>}<footer><button className="button secondary" onClick={()=>setShowAdd(false)}>Cancel</button><button className="button" disabled={saving||!form.name||!form.email||!form.serviceId} onClick={createBooking}>{saving?"Creating…":"Create booking"}</button></footer></div></div>}
  </div>;
}
