"use client";

import Link from "next/link";
import { ArrowRight, Download, Mail, Phone, Plus, Search, SlidersHorizontal, UserPlus, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { customers as seedCustomers } from "@/lib/demo-data";
import { initials, money, shortDate } from "@/lib/format";
import type { Customer } from "@/lib/types";

const blankClient={name:"",email:"",phone:"",texture:"Not set",preferredStyle:"",notes:""};
export default function ClientsPage() {
  const [clients,setClients]=useState<Customer[]>(seedCustomers);
  const [query,setQuery]=useState("");
  const [segment,setSegment]=useState("all");
  const [showAdd,setShowAdd]=useState(false);
  const [newClient,setNewClient]=useState(blankClient);
  const [saving,setSaving]=useState(false);
  useEffect(()=>{fetch("/api/dashboard/data?resource=clients").then(r=>r.json()).then(payload=>{if(Array.isArray(payload.data))setClients(payload.data)}).catch(()=>undefined)},[]);
  const filtered=useMemo(()=>clients.filter(customer=>{const matchesQuery=`${customer.name} ${customer.email} ${customer.phone} ${customer.preferredStyle}`.toLowerCase().includes(query.toLowerCase());const joined=new Date(customer.joinedAt);const isNew=Date.now()-joined.getTime()<=30*86400000;const matchesSegment=segment==="all"||(segment==="returning"&&customer.visits>1)||(segment==="new"&&isNew)||(segment==="high_value"&&customer.lifetimeValueCents>=20000)||(segment==="needs_preferences"&&(!customer.preferredStyle||customer.preferredStyle==="Not set"));return matchesQuery&&matchesSegment}),[clients,query,segment]);
  const totalValue=clients.reduce((sum,client)=>sum+client.lifetimeValueCents,0);
  const totalVisits=clients.reduce((sum,client)=>sum+client.visits,0);
  function exportClients(){const rows=[["Name","Email","Phone","Texture","Preferred Style","Visits","Lifetime Value"],...clients.map(client=>[client.name,client.email,client.phone,client.texture,client.preferredStyle,client.visits,(client.lifetimeValueCents/100).toFixed(2)])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download="cutflow-clients.csv";link.click();URL.revokeObjectURL(url)}
  async function createClient(){setSaving(true);const response=await fetch("/api/dashboard/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"client",item:newClient})});const payload=await response.json();if(response.ok&&Array.isArray(payload.data)){setClients(payload.data);setShowAdd(false);setNewClient(blankClient)}setSaving(false)}
  return <div className="dashboard-page clients-page"><header className="page-header"><div><p className="eyebrow">PRIVATE CLIENT DIRECTORY</p><h1>Clients</h1><p>Every booking grows a useful profile with service history, preferences and lifetime activity.</p></div><div className="page-actions"><button className="button secondary" onClick={exportClients}><Download/> Export clients</button><button className="button" onClick={()=>setShowAdd(true)}><UserPlus/> Add client</button></div></header>
  <section className="client-stats metric-grid compact"><article className="metric-card glass-card"><p>Total clients</p><strong>{clients.length}</strong><small>Profiles in this workspace</small></article><article className="metric-card glass-card"><p>Total visits</p><strong>{totalVisits}</strong><small>Completed appointments</small></article><article className="metric-card glass-card"><p>Average client value</p><strong>{money(clients.length?Math.round(totalValue/clients.length):0)}</strong><small>Lifetime average</small></article><article className="metric-card glass-card"><p>Profiles with preferences</p><strong>{clients.length?Math.round((clients.filter(client=>client.preferredStyle&&client.preferredStyle!=="Not set").length/clients.length)*100):0}%</strong><small>Saved style information</small></article></section>
  <div className="table-toolbar dashboard-card"><label className="search-field"><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search name, phone, email or style"/></label><label className="transaction-filter"><SlidersHorizontal/><span className="sr-only">Filter clients</span><select value={segment} onChange={(event)=>setSegment(event.target.value)}><option value="all">All clients</option><option value="returning">Returning clients</option><option value="new">New in 30 days</option><option value="high_value">$200+ lifetime value</option><option value="needs_preferences">Missing cut preferences</option></select></label></div>
  <section className="client-table dashboard-card"><header><span>Client</span><span>Last visit</span><span>Visits</span><span>Preferred cut</span><span>Lifetime value</span><span/></header>{filtered.map(customer=><Link href={`/dashboard/clients/${customer.id}`} className="client-row" key={customer.id}><span className="client-identity"><i className="avatar">{initials(customer.name)}</i><span><b>{customer.name}</b><small><Mail/> {customer.email}</small><small><Phone/> {customer.phone}</small></span></span><span><b>{shortDate(customer.lastVisit)}</b><small>{Math.max(0,Math.round((Date.now()-new Date(customer.lastVisit).getTime())/86400000))} days ago</small></span><span><b>{customer.visits}</b><small>since {new Date(customer.joinedAt).getFullYear()}</small></span><span><b>{customer.preferredStyle||"Not set"}</b><small>{customer.texture||"Not set"} texture</small></span><span><b>{money(customer.lifetimeValueCents)}</b><small>{customer.visits?money(Math.round(customer.lifetimeValueCents/customer.visits)):"$0.00"} avg.</small></span><ArrowRight/></Link>)}{filtered.length===0&&<div className="empty-selection"><Search/><p>No clients found.</p></div>}</section>
  {showAdd&&<div className="modal-scrim"><div className="modal-card glass-card"><header><div><p className="eyebrow">NEW CLIENT PROFILE</p><h2>Add someone before they book.</h2></div><button className="icon-button" onClick={()=>setShowAdd(false)}><X/></button></header><div className="form-grid two"><label><span>Full name</span><input value={newClient.name} onChange={event=>setNewClient({...newClient,name:event.target.value})} placeholder="Client name"/></label><label><span>Mobile number</span><input value={newClient.phone} onChange={event=>setNewClient({...newClient,phone:event.target.value})} placeholder="(508) 555-0123"/></label><label className="full"><span>Email</span><input value={newClient.email} onChange={event=>setNewClient({...newClient,email:event.target.value})} type="email" placeholder="client@example.com"/></label><label><span>Hair texture</span><select value={newClient.texture} onChange={event=>setNewClient({...newClient,texture:event.target.value})}><option>Not set</option><option>3C</option><option>4A</option><option>4B</option><option>4C</option></select></label><label><span>Preferred style</span><input value={newClient.preferredStyle} onChange={event=>setNewClient({...newClient,preferredStyle:event.target.value})} placeholder="Low taper + textured top"/></label><label className="full"><span>Private barber notes</span><textarea value={newClient.notes} onChange={event=>setNewClient({...newClient,notes:event.target.value})} placeholder="Preferences, sensitivities, conversation notes…"/></label></div><footer><button className="button secondary" onClick={()=>setShowAdd(false)}>Cancel</button><button className="button" disabled={saving||!newClient.name||!newClient.email} onClick={createClient}><Plus/> {saving?"Creating…":"Create profile"}</button></footer></div></div>}</div>;
}
